### ISSUE TITLE
Pyomeca on Google Colab?

### ISSUE THREAD

**Issue by joselvira** [pyomeca/pyomeca#114]
First of all, thank you for your effort developing pyomeca, I find it fantastic!
My only concern is about the installation process in some environments such as Google Colab or even Winpython. Is it possible to install it via pip or other easy to use command?

Thank you for your time.

**Comment by romainmartinez** [comment]
Hi @joselvira,

Unfortunately, `pyomeca` is only available as a `conda` package at the moment.
It would be easy to make it available on `pip` since it is a pure python package.
The only problem is that one of the dependencies — [`ezc3d`](https://github.com/pyomeca/ezc3d) — is not available on `pip`.
As long as `ezc3d` is not on `pip`, `pyomeca` will only be available on `conda`.

1. Use `conda` in `colab`. A simple google search indicates that this is easily done: [here](https://stackoverflow.com/questions/59330876/install-conda-package-to-google-colab), [here](https://towardsdatascience.com/conda-google-colab-75f7c867a522) or [here](https://medium.com/@dvij.kalaria/how-to-make-load-save-a-conda-environment-in-google-colab-jupyter-322801aad486).
2. Help us put `ezc3d` on pip. There is already a discussion [here](https://github.com/pyomeca/ezc3d/issues/111) with @pariterre.
3. Use an alternative to `colab` like [`binder`](https://mybinder.org/) or directly use miniconda locally on your computer.

**Comment by pariterre** [comment]
After trying hard enough, I can confirm that I won't port ezc3d on pip. Therefore, @joselvira, you will have to use a workaround.
Please note that the issue of using ezc3d in a google colab environment was discussed there https://github.com/pyomeca/ezc3d/issues/168. The method allows for any conda package to be used

@romainmartinez I think this issu can be closed
