### ISSUE TITLE
Problem With Google Colab Import

### ISSUE THREAD

**Issue by jrdunga** [pyomeca/pyomeca#127]
Problem With Google Colab Import

I can not import pyomeca or ezc3d in Google Colab environment.

When I put

```python

# Install miniconda environment
!wget -c https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
!chmod +x Miniconda3-latest-Linux-x86_64.sh
!bash ./Miniconda3-latest-Linux-x86_64.sh -b -f -p /usr/local

import sys
sys.path.append('/usr/local/lib/python3.9/site-packages/')

# Download and install desired packages
!conda install -y --prefix /usr/local -c pyomeca -c conda-forge pyomeca

# Enjoy the packages
import ezc3d
import pyomeca

```

I receive in return
```

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-8-471790ada190> in <module>()
      1 # Enjoy the packages
----> 2 import ezc3d
      3 import pyomeca

ModuleNotFoundError: No module named 'ezc3d'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------
```
The same error occurs if I try to import piomeca.
I already tried to change

```

# Download and install desired packages
!conda install -y --prefix /usr/local -c pyomeca -c conda-forge pyomeca
```

for
```

# Download and install desired packages
!conda install -y --prefix /usr/local -c pyomeca=3.9 -c conda-forge pyomeca
```
but I keep getting the same error.

Thanks.

**Comment by pariterre** [comment]
Dear @jrdunga 

Google Colab is a picky on which version of Python you using when installing packages though conda. The conda version and colab versions has to match. Otherwise it won't find the packages or it will not be able to import the libraries. 

Therefore, when installing pyomeca and ezc3d, you have to force the version to be the same as the Colab's one. Currently, it is the 3.7 version (but it can change anytime...). 
So the install command should look like this:

```python
!conda install pyomeca python=3.7 -cconda-forge
```
Note the `python=3.7` which may have to change if the underlying python version of Google Colab changes

Similarly the `sys.path.append('/usr/local/lib/python3.7/site-packages/')` should refer to the 3.7 version (and not the 3.9 version)

Hope this helps!

**Comment by jrdunga** [comment]
I did it but the problem remains.  I could Pyomeca on Google Colab a few days ago. But it stopped working. I try to do your suggestion but I keeping with the problem. I can use Pyomeca in my computer :smiley:  but not in Colab 😡 . I will keeping try.

**Comment by pariterre** [comment]
The command that works here:

```python
!wget -c https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
!chmod +x Miniconda3-latest-Linux-x86_64.sh
!bash ./Miniconda3-latest-Linux-x86_64.sh -b -f -p /usr/local

!conda install ezc3d python=3.7 -cconda-forge -y

import sys
_ = (sys.path.append("/usr/local/lib/python3.7/site-packages"))
```
```python
import ezc3d
import pyomeca
```

**Comment by jrdunga** [comment]
Now everything all right. I changed 
```

# Download and install desired packages
!conda install -y --prefix /usr/local -c pyomeca -c conda-forge pyomeca
```

to 

```
# Download and install desired packages
!conda install ezc3d python=3.7 -cconda-forge -y
!conda install pyomeca python=3.7 -cconda-forge -y

```

and it's all working now.

Thank you one more time.
